apiVersion: v1
kind: Pod
metadata:
    name: test-app
spec:
  containers:
  - image: lmi:latest
    name: simple-pod
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
      name: out
